import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///data/market_data.db")

DEFAULT_SYMBOLS = ["BTCUSDT", "ETHUSDT"]

TICK_BUFFER_SIZE = 10000

BATCH_SIZE = 100

FLUSH_INTERVAL = 1.0

RESAMPLER_INTERVAL = 5.0

ANALYTICS_INTERVAL = 1.0

TIMEFRAMES = ['1s', '1m', '5m']

DEFAULT_ROLLING_WINDOW = 20

API_HOST = "0.0.0.0"
API_PORT = 8000

DASHBOARD_PORT = 8501

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")